/**
 * Programmatic migrations (research R10): the API runs this at boot, before
 * binding its port, so a process that answers /ready is schema-current by
 * construction — there is no separate "run migrations" deploy step to forget.
 * SQL files are generated by drizzle-kit (see drizzle.config.ts) into
 * ../migrations; this module only applies them.
 */
import { fileURLToPath } from "node:url";

import { migrate as drizzleMigrate } from "drizzle-orm/node-postgres/migrator";

import type { Database } from "./client";

// Resolved relative to this module (not process cwd) so migrations are found
// no matter which app's working directory the process was launched from.
const MIGRATIONS_FOLDER = fileURLToPath(new URL("../migrations", import.meta.url));

// Idempotent: drizzle tracks applied migrations in its own journal table, so
// every boot can call this unconditionally.
export async function runMigrations(db: Database): Promise<void> {
  await drizzleMigrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
}
